### ISSUE TITLE
issue with chromadb

### ISSUE THREAD

**Issue by kartheekyakkala** [cirediatpl/FigmaChain#5]
![Screenshot 2023-05-03 at 4 05 50 PM](https://user-images.githubusercontent.com/50788154/235893534-52d02deb-166d-43fc-833b-e8d671158832.png)

when I give **python generateCode.py <input>** it throws this error **NameError: name 'chromadb' is not defined** . First time it threw module not found error, after I installed it using pip it started throwing this new error NameError. Someone please help me in fixing this.

Thanks in advance :).

**Comment by huanshare** [comment]
Traceback (most recent call last):
  File "generateCode.py", line 27, in <module>
    index = VectorstoreIndexCreator().from_loaders([figma_loader])
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/langchain/indexes/vectorstore.py", line 71, in from_loaders
    vectorstore = self.vectorstore_cls.from_documents(
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/langchain/vectorstores/chroma.py", line 398, in from_documents
    return cls.from_texts(
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/langchain/vectorstores/chroma.py", line 359, in from_texts
    chroma_collection = cls(
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/langchain/vectorstores/chroma.py", line 71, in __init__
    raise ValueError(
ValueError: Could not import chromadb python package. Please install it with `pip install chromadb`.
how to solve it ???

**Comment by dev-dux** [comment]
Try `pip install chromadb==0.3.29`.
